# Generated by Django 4.1.7 on 2023-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='Category_Img')),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
