# Generated by Django 4.1.7 on 2023-05-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('May', '0004_remove_productdb_pcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(blank=True, max_length=50, null=True)),
                ('CEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('CSubject', models.CharField(blank=True, max_length=50, null=True)),
                ('CMessage', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
