# Generated by Django 4.1.7 on 2023-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(blank=True, max_length=50, null=True)),
                ('UEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('UPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('UPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('UImage', models.ImageField(blank=True, null=True, upload_to='User_Profile')),
            ],
        ),
    ]
