# Generated by Django 4.1.7 on 2023-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(blank=True, max_length=50, null=True)),
                ('Product', models.CharField(blank=True, max_length=50, null=True)),
                ('PDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Product_In_Cart')),
            ],
        ),
    ]
